version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-marketmap}
      POSTGRES_USER: ${DB_USER:-marketmap}
      POSTGRES_PASSWORD: ${DB_PASS:-marketmap}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-marketmap} -d ${DB_NAME:-marketmap}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-marketmap}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-marketmap}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS:-marketmap}
      # optional tunables:
      # JAVA_OPTS: -Xms256m -Xmx512m
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"   # open http://localhost:5173
    # no env needed; nginx proxies /api to backend

volumes:
  db_data:
